In [28]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

In [41]:
n=1000

data={"Age":np.random.randint(15,50,n),  #age between 15 to 50
      "Genre":np.random.randint(0,5,n),  #movies category (action=0, drama=1,fiction=2, comedy=3, horror=4)
      "Rating":np.random.randint(1,6,n), # rating from 1 to 5 star
      "WatchTime":np.random.randint(10,180,n)  # watch time 10min to 180 min)
     }

In [42]:
df=pd.DataFrame(data)
df

     Age  Genre  Rating  WatchTime
0     33      3       3        126
1     35      0       5        142
2     47      0       5         68
3     20      3       1        168
4     46      0       5        151
..   ...    ...     ...        ...
995   40      3       5        156
996   18      1       1         39
997   48      1       3         61
998   33      2       3         78
999   44      4       3         21

[1000 rows x 4 columns]

In [43]:
#rule-based
df['Like']=(
    (df['Rating'] >3)&
    (df['WatchTime'] >60 )).astype(int)

In [44]:
df

     Age  Genre  Rating  WatchTime  Like
0     33      3       3        126     0
1     35      0       5        142     1
2     47      0       5         68     1
3     20      3       1        168     0
4     46      0       5        151     1
..   ...    ...     ...        ...   ...
995   40      3       5        156     1
996   18      1       1         39     0
997   48      1       3         61     0
998   33      2       3         78     0
999   44      4       3         21     0

[1000 rows x 5 columns]

In [45]:
#split
x=df.drop("Like",axis=1)
y=df["Like"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
scale=StandardScaler()

x_train=scale.fit_transform(x_train)    # it calculates the mean and SD of each features in training set
x_test=scale.transform(x_test)

In [47]:
model=Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(12,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='sigmoid')])

In [48]:
#compile
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

In [49]:
# train model
model.fit(x_train,y_train,epochs=20,batch_size=16)

Epoch 1/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7125 - loss: 0.5204
Epoch 2/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7325 - loss: 0.4397
Epoch 3/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.3781
Epoch 4/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8462 - loss: 0.3295
Epoch 5/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8988 - loss: 0.2883
Epoch 6/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9438 - loss: 0.2509
Epoch 7/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9588 - loss: 0.2139
Epoch 8/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9675 - loss: 0.1800
Epoch 9/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9712 - loss: 0.1504
Epoch 10/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9737 - loss: 0.1264
Epoch 11/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9775 - loss: 0.1075
Epoch 12/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9800 - loss: 0.0926
Epoch 13/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9787 - loss: 0.0821
Epoch 14/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9800 - loss: 0.0713
Epoch 15/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9825 - loss: 0.0642
Epoch 16/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9800 - loss: 0.0588
Epoch 17/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9825 - loss: 0.0539
Epoch 18/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9825 - loss: 0.0510
Epoch 19/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.0471
Epoch 20/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9862 - loss: 0.0445

In [50]:
# evaluation
loss,accuracy=model.evaluate(x_test,y_test)
print("Accuracy:",accuracy)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9750 - loss: 0.0438
Accuracy: 0.9750000238418579

In [51]:
#test new data
new_data=np.array([[26,3,4.5,140]])  # age,genre,rating,watchtime

In [52]:
new_data_scale=scale.transform(new_data)

C:\Users\Akrit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [53]:
predict=model.predict(new_data_scale)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

In [54]:
final=(predict > 0.5).astype(int)

print("Prediction 0=Dislike 1=Like:",final[0][0])

Prediction 0=Dislike 1=Like: 1